#!/bin/bash

installdir="/home/$USER/bin/hackerspace-scripts-2"
FILE="/home/$USER/.profile"
localdir="$(pwd)"
string="export PATH=\$PATH:$localdir/"

cd $installdir

echo "### UPDATING ###"

git pull

if grep -q "$string" $FILE; then
    echo "Already installed\n"
else
    echo "### INSTALLING COMMAND ###"
    echo -e "export PATH=\$PATH:$localdir/" >> $FILE
    echo "Next time you can log out then back in to use 'control-panel' anywhere from the command line.\n"
fi

if ! test -f "$installdir/env/bin/activate"; then
    echo "\n### INSTALLING PYTHON ENVIRONMENT ###\n"
    python3 -m venv $installdir/env
fi

source $installdir/env/bin/activate

echo "\n### UPDATING PYTHON ENVIRONMENT ###\n"
pip install -r requirements.txt

echo "\n### CHECKING INSTALLED PACAKGES ###\n"
python $installdir/bootstrap.py

echo "\n### RUNNING CONTROL PANEL ###\n"
python $installdir/controlpanel.py